#!/usr/bin/env python

import qmaze

controller = qmaze.RandomController()
game = qmaze.Game(controller)

time = 0
while game.next() is not None:
    time += 1
    game.show()

print('elapsed time: {}'.format(time))